final products = [
  {
    'id':'1',
    'title':'Retropy F2 Shoes',
    'price': 7679.50,
    'imageUrl': 'assets/images/Adidas_1.png',
    'company':'Adidas',
    'sizes' : [4 ,5 ,7 , 8 ],
  },
  {
    'id':'2',
    'title':'Dropset Training Shoes',
    'price': 10799.50,
    'imageUrl': 'assets/images/Adidas_2.png',
    'company':'Adidas',
    'sizes' : [4 ,6],
  },
  {
    'id':'3',
    'title':'Ultraboost DNA Shoes',
    'price': 22999.00,
    'imageUrl': 'assets/images/Adidas_3.png',
    'company':'Adidas',
    'sizes' : [4 ,5 , 6 ,7 , 8],
  },
  {
    'id':'4',
    'title':'Ultraboost 1.0 shoes',
    'price': 10799.50,
    'imageUrl': 'assets/images/Adidas_4.png',
    'company':'Adidas',
    'sizes' : [4 , 6 ,7 ],
  },
  {
    'id':'1',
    'title':'P-6000 PRM',
    'price': 11495.00,
    'imageUrl': 'assets/images/Nike_1.png',
    'company':'Nike',
    'sizes' : [4 ,5 , 6 ,7 ],
  },
  {
    'id':'2',
    'title':'Air Jordan 4 RM',
    'price': 12795.00,
    'imageUrl': 'assets/images/Nike_2.png',
    'company':'Nike',
    'sizes' : [3, 4 ,5 , 6 ,7 ],
  },
  {
    'id':'3',
    'title':'Air Max Koko',
    'price': 7995.00,
    'imageUrl': 'assets/images/Nike_3.png',
    'company':'Nike',
    'sizes' : [3 ,4 ,5 , 6 ],
  },
  {
    'id':'4',
    'title':'Shox TL',
    'price': 15995.00,
    'imageUrl': 'assets/images/Nike_4.png',
    'company':'Nike',
    'sizes' : [3 , 4 ,5 , 6 ],
  },
  {
    'id':'1',
    'title':'Scuderia Ferrari Motorsport Sneakers',
    'price': 10999.00,
    'imageUrl': 'assets/images/Puma_1.png',
    'company':'Puma',
    'sizes' : [3 ,4 ,5 , 6 ,7 ,8 ],
  },
  {
    'id':'2',
    'title':'X-Ray 2 Square Superior Sneakers',
    'price': 7999.00,
    'imageUrl': 'assets/images/Puma_2.png',
    'company':'Puma',
    'sizes' : [4 ,5 , 6 ,7 ],
  },
  {
    'id':'3',
    'title':'CA Pro Classic Leather Sneakers',
    'price': 5999.00,
    'imageUrl': 'assets/images/Puma_3.png',
    'company':'Puma',
    'sizes' : [4 ,5 , 6 ,7 , 8 ],
  },
  {
    'id':'4',
    'title':'Palermo Supertifo Sneakers',
    'price': 7999.00,
    'imageUrl': 'assets/images/Puma_4.png',
    'company':'Puma',
    'sizes' : [ 6 ,7 , 8],
  },
  {
    'id':'1',
    'title':'Chuck 70 De Luxe Wedge Leather',
    'price': 10999.00,
    'imageUrl': 'assets/images/Converse_1.png',
    'company':'Converse',
    'sizes' : [4 , 5 , 6 ,7 ],
  },
  {
    'id':'2',
    'title':'Chuck 70 Canvas Seasonal',
    'price': 6399.00,
    'imageUrl': 'assets/images/Converse_2.png',
    'company':'Converse',
    'sizes' : [3 ,5 , 6 ,7,8 ],
  },
  {
    'id':'3',
    'title':'Chuck Taylor All Star Cosmic',
    'price': 5999.00,
    'imageUrl': 'assets/images/Converse_3.png',
    'company':'Converse',
    'sizes' : [5 , 6 ,7 ],
  },
  {
    'id':'4',
    'title':'Chuck Taylor All Star Leather',
    'price': 7999.00,
    'imageUrl': 'assets/images/Converse_4.png',
    'company':'Converse',
    'sizes' : [5 , 6 ,7 , 8],
  },
];